---
name: Run examples (reusable workflow)

on:
  workflow_call:

concurrency:
  cancel-in-progress: true
  group: >-
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  run-examples:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: 3.14

      - name: Cache nox
        uses: actions/cache@v4
        with:
          key:
            examples-${{ hashFiles('pyproject.toml') }}-${{
            hashFiles('noxfile.py') }}
          path: .nox

      - name: Install only dev dependencies
        run: uv sync --only-dev

      - name: Run examples
        run: uv run nox -s examples
        timeout-minutes: 20
        env:
          FORCE_COLOR: 1

      - name: Generate HTML
        run: uv run nox -s examples -- html
        env:
          FORCE_COLOR: 1

      - name: Upload artefact
        uses: actions/upload-artifact@v6
        with:
          name: Examples
          path: examples/**/*.html
